"""
Django settings for stock_guard project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# This value is a dev-only sentinel. It is only used when SECRET_KEY is absent
# from the environment, i.e. during local development. In production SECRET_KEY
# must be injected as an env var; a missing key fails the start loudly rather
# than silently running with the committed insecure value.
_DEV_INSECURE_SECRET_KEY = 'django-insecure-+4mhx9fvrm-me5zx%r@gl4m3gsiu%hf6xbfqf@)_y#=-ph*23_'

SECRET_KEY = os.environ.get('SECRET_KEY', _DEV_INSECURE_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Production default is False. The dev fallback only flips DEBUG on when the
# secret key is the committed dev sentinel, so a prod deploy missing SECRET_KEY
# fails rather than accidentally exposing a debug page.
DEBUG = os.environ.get('DEBUG', '').lower() in ('1', 'true', 'yes')

if SECRET_KEY == _DEV_INSECURE_SECRET_KEY:
    DEBUG = True

ALLOWED_HOSTS = [host for host in os.environ.get('ALLOWED_HOSTS', '').split(',') if host]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stock_guard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stock_guard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# In production DATABASE_URL (injected by Railway) points at Postgres;
# dj-database-url parses it and enables connection reuse plus TLS.
# Locally (no DATABASE_URL) we keep SQLite as the dev default.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Security
# Railway terminates HTTPS at its proxy; trust its forwarded-proto header and
# mark cookies secure outside local development.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Django 6.1 flags the console backend as a deploy ERROR (mail.E001). The PRD
# has no email requirement in MVP, but the SMTP backend is selected whenever
# EMAIL_HOST is configured so `check --deploy` passes and a future email feature
# needs no settings change; console stays the local-dev default.
if os.environ.get('EMAIL_HOST'):
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'HOST': os.environ.get('EMAIL_HOST'),
            'PORT': int(os.environ.get('EMAIL_PORT', '587')),
            'USERNAME': os.environ.get('EMAIL_USER'),
            'PASSWORD': os.environ.get('EMAIL_PASSWORD'),
            'USE_TLS': os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes'),
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }
